language: bash
script:
- export DOCKER_HUB_USERNAME=groundworkbot
- export BUILD_ARGS="--build-arg GITHUB_TOKEN"
- make --warn-undefined-variables -f travis.Makefile all
notifications:
  slack:
    rooms:
      secure: pFDAZTuaS3g+wekOfe8MXZ8yJcpTOVvupHCupPztwuOLT2k1cbX/hhG13vHIZ9dyqiTIIU7Km7VrxizlKsA25v2ymY5eDwAkmZ/M1X2KceDKtWi3mJ0o/EKeGiiSPk1V3lg2CGVjunf4wuYzd6VeDB90HF2KbtVOvmOVGO06aRYFmTk7m+WTpeHKt+pAG7sBEgzUY8SxCLc3haRSrB/IEpPzCkKivXzQYKzVGVYxx87GGDp63aIfHRCIk3kRmhXB6KTXULMWTCv0nYx9RrDXlaHE9qLRyl0ncogOaBVWdwVo84F61uuhjr/Ss2a2ZZRTj/myEdLcFJpyqbFwmvHLIvnbgbkbLvVv+mNlwV7xV3frIEFROPQyp1500WQm3MSo1/pXrGRtSEuYIFAFmxYsDp4MrZjU4iXvJDIh0GAljDKchHLPcDVylaIdGJ9opkBz0B5wa1Xf1zWZ4dON4zKqXwfRRvd3jVJdPudjFcUMl7tEpJgtUkfO0hf8Z8e4nUYMrvmZ2wu8C046V3pQUJ8I4qu4WU2yu04Jrjc2LYea0bISfHz6QwH+omSR6Lp0GAhcWVtPfUoONmmt8xfWe+DCsEyWw3vCRZWkyGhSbx8J1wQx/L8KrAFm6Mv0nYXGdL9GJP44K0ACOlVLuK3nQTzBzjwXSe4NtHv/KLLSgYoqISY=
    on_pull_requests: true
  webhooks:
    urls:
    - http://demo.gwos.com/services/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
