language: bash
script:
- export DOCKER_HUB_USERNAME=groundworkbot
- export BUILD_ARGS="--build-arg GITHUB_TOKEN"
- make --warn-undefined-variables -f travis.Makefile all
notifications:
  slack:
    rooms:
      secure: Vj/h5hUUL77QKaj/lijUOqdqRswwRPF0VJhNvW5UfALdrVBoX+QvUFJ2T/RcMCwkq36BZaU5T6LkohUtqa2gEwwmYAN7JCSEg22sQTrZ8ONzvHXH770VJGyHOoHGEyoVbbx4x/3V6J2yO1JcoRH1kyM2Seuwo03Ia7YZ4HQCB14yR36zx7Kt7yZjaQP33OhBydbnuAVPfVxUW0hoC11vEhfS0g6CgFTDD7LFmluQ4VGnTtGZNj7OvZ5MhFNh8McYzYk19Bak2N67zZwM/0Ix1DOY/Bvda6oOjV3Are46TJo3WE7iNTEBurPE9ZSsqtD8XqUz4LcLZ/pLhWhLRAaCzuX7BQRlnVPxupQpjWqEcK47hLYrslQGXFR+9nWsYmJLTPEhfYYdwcjEUgDCMlhkuV60BfxSJBx6iHEJq1WAdkagaVNQOzqFTq2cz9XKKc5I/Lzi9ds8pIzVFdX/3rn+ZAcuMCFmXlzqZ7RDKd14P6SOMYJ/w1nr+hQPQQdTT0jr6wAu6Y+YQ8AOi0+gJdkSti/f90FARt0aYmOq1cAAJyA7Ev85iQGiOwePgyv4tXggddvdRP34z03ZMWDXL47VZRw7Wh6uQQ0vpma+2mu9oo6ueR1kkgRxmLA8yd9PZwnnrkyDUUQSRlargnNsEhyPQapful+DpR1fDUISHyAumXM=
    on_pull_requests: true
  webhooks:
    urls:
    - http://demo.gwos.com/services/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
